accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.LogoutPageView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangePageView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDonePageView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetPageView.as_view(), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDonePageView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmPageView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompletePageView.as_view(), name='password_reset_complete'),
    path('signup/', views.SignUpPageView.as_view(), name="signup"),
    path('profile/', views.profile_page_view, name='profile'),
    # path('profile/update/<int:pk>/', views.ProfileUpdatePageView.as_view(), name='profile_update'),
    path('profile/update/<int:pk>/', views.profile_update_page_view, name='profile_update'),
    path('profile/create/<int:id>', views.ProfileCreatePageView.as_view(), name='profile_create'),
]

epica_test/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('pica.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pica/urls.py
from django.urls import path
from . import views

app_name = "pica"
urlpatterns = [
    path('', views.home, name="home"),
    path('create_departemen/', views.CreateDepartemenView.as_view(), name="create_departemen"),
    path('update_departemen/<int:pk>/', views.UpdateDepartemenView.as_view(), name="update_departemen"),
    path('delete_departemen/<int:pk>/', views.DeleteDepartemenView.as_view(), name="delete_departemen"),
    path('create_forum/', views.CreateForumView.as_view(), name="create_forum"),
    path('update_forum/<int:pk>/', views.UpdateForumView.as_view(), name="update_forum"),
    path('delete_forum/<int:pk>/', views.DeleteForumView.as_view(), name="delete_forum"),
    path('create_company/', views.CreateCompanyView.as_view(), name="create_company"),
    path('update_company/<int:pk>/', views.UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<int:pk>/', views.DeleteCompanyView.as_view(), name="delete_company"),
    path('create_peserta/', views.CreatePesertaView.as_view(), name="create_peserta"),
    path('update_peserta/<int:pk>/', views.UpdatePesertaView.as_view(), name="update_peserta"),
    path('delete_peserta/<int:pk>/', views.DeletePesertaView.as_view(), name="delete_peserta"),
    path('add_peserta/<int:pk>/', views.add_peserta, name="add_peserta"),
    path('masukkan_peserta/<int:pk1>/<int:pk2>/', views.masukkan_peserta, name="masukkan_peserta"),
    path('hapus_peserta/<int:pk1>/<int:pk2>/', views.hapus_peserta, name="hapus_peserta"),
    path('create_pica/<int:pk>/', views.create_pica, name="create_pica"),
    path('update_pica/<int:pk1>/<int:pk2>/', views.update_pica, name="update_pica"),
    path('update_pica_action/<int:pk1>/<int:pk2>/', views.update_pica_action, name="update_pica_action"),
    path('add_pic/<int:pk1>/<int:pk2>/', views.add_pic, name="add_pic"),
    path('meet_render_pdf/<int:pk>/', views.meet_render_pdf, name="meet_render_pdf"),
    path('meet_signature_pdf/<int:pk>/', views.meet_signature_pdf, name="meet_signature_pdf"),
    path('send_meet_render_pdf/<int:pk>/', views.send_meet_render_pdf, name="send_meet_render_pdf"),
    path('masukkan_pic/<int:pk1>/<int:pk2>/<int:pk3>/<str:pk4>/', views.masukkan_pic, name="masukkan_pic"),
    path('hapus_pic/<int:pk1>/<int:pk2>/<int:pk3>/', views.hapus_pic, name="hapus_pic"),
    path('create_meeting/', views.CreateMeetingView.as_view(), name="create_meeting"),
    path('history_meeting/', views.history_meeting, name="history_meeting"),
    path('meeting_dashboard/<int:pk>/<int:hs>/', views.meeting_dashboard, name="meeting_dashboard"),
    path('update_dashboard/<int:pk>/', views.UpdateDashboardView.as_view(), name="update_dashboard"),
    path('list_pica/<int:pk>/', views.list_pica, name="list_pica"),
    path('create_activity/<int:pk>/', views.create_activity, name="create_activity"),
    path('update_activity/<int:pk>/', views.update_activity, name="update_activity"),
    path('delete_activity/<int:pk>/', views.delete_activity, name="delete_activity"),
    path('list_activity/<int:pk>/<int:ctr>/', views.list_activity, name="list_activity"),
    path('add_topik/<int:pk>/', views.add_topik, name="add_topik"),
    path('delete_topik/<int:pk1>/<int:pk2>/', views.delete_topik, name="delete_topik"),
    path('masukkan_topik/<int:pk1>/<int:pk2>/', views.masukkan_topik, name="masukkan_topik"),
    path('hapus_topik/<int:pk1>/<int:pk2>/', views.hapus_topik, name="hapus_topik"),
    path('topik_expired_check/', views.topik_expired_check, name="topik_expired_check"),
    path('list_open_pica/', views.list_open_pica, name="list_open_pica"),
    path('search_topik/', views.search_topik, name="search_topik"),
    path('search_all/', views.search_all, name="search_all"),
    path('notify_all/', views.notify_all, name="notify_all"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
{% include 'show_messages.html' %}
{% block content %}
{% endblock %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src=" {% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src=" {% static 'js/popper.min.js' %}"></script>
</body>
</html>

templates/base_pdf.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src=" {% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src=" {% static 'js/popper.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-lg-4 offset-lg-4 text-center">
            <img src="{% static 'images/ePicaLogo.png' %}" alt="epica logo">
            <br>
        </div>
        {% if user.username == 'admin' %}
            <div class="py-5">
                <div class="row">
                    {% for meeting in meetings %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <div class="card-header row">
                                    <h5>
                                        Meeting {{ meeting.meeting2forum.nama_forum }} </h5>
                                </div>
                                <div class="card-body">
                                    <h6 class="card-title">
                                        {{ meeting.meeting_date | date:"l, d F Y" }}
                                    </h6>
                                    <p class="card-text">Start Time : {{ meeting.start_time |time:"G:i A"}}</p>
                                    <p class="card-text">End Time : {{ meeting.end_time |time:"G:i A"}}</p>
                                    <p class="card-text">Notulen : {{ meeting.notulen }}</p>
                                    <p class="card-text">Location : {{ meeting.location }}</p>
                                    <a href="{% url 'pica:meeting_dashboard' meeting.pk 1 %}" class="card-link">Meeting Dashboard
                                        </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="py-5">
                <div class="row">
                    {% for topik in topiks %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <div class="card-header row">
                                    <h5>
                                        Meeting {{ topik.topik2meeting.meeting2forum.nama_forum }} {{ topik.topik2meeting.meeting_date | date:"l, d F Y" }}</h5>
                                </div>
                                <div class="card-body">
                                    <h6 class="card-title">
                                        {{ topik.nama_topik|truncatechars:50 }}
                                    </h6>
                                    <p class="card-text">Problem:</p>
                                    <p class="card-text">{{ topik.problem|safe }}</p>
                                    <p class="card-text">Action/Information:</p>
                                    <p class="card-text">{{ topik.action|safe }}</p>
                                    <p class="card-text">Due date:</p>
                                    <p class="card-text">{{ topik.due_date | date:"l, d F Y" }}</p>
                                    <a href="{% url 'pica:create_activity' topik.pk %}" class="card-link">Input
                                        Activity</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="{% url 'pica:home' %}"><img src="{% static 'images/ePicaLogo50.png' %}" alt="ePica logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        PICA
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'pica:create_meeting' %}">Meeting</a>
                        <a class="dropdown-item" href="{% url 'pica:history_meeting' %}">History Meeting</a>
                        <a class="dropdown-item" href="{% url 'pica:create_departemen' %}">Function</a>
                        <a class="dropdown-item" href="{% url 'pica:create_forum' %}">Forum</a>
                        <a class="dropdown-item" href="{% url 'pica:create_company' %}">Company</a>
                        <a class="dropdown-item" href="{% url 'pica:create_peserta' %}">Peserta</a>
                        <a class="dropdown-item" href="{% url 'pica:list_pica' user.id %}">Activity</a>
                        <a class="dropdown-item" href="{% url 'pica:topik_expired_check'%}">Status PICA</a>
                        <a class="dropdown-item" href="{% url 'pica:list_open_pica'%}">List Open PICA</a>
                        <a class="dropdown-item" href="{% url 'pica:search_topik'%}">Search PICA</a>
                        <a class="dropdown-item" href="{% url 'pica:search_all'%}">Search All</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if user.user2profile %}
                            <a class="dropdown-item" href="{% url 'accounts:profile_update' user.user2profile.pk %}">Update
                                Profile</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:profile_create' user.id %}">Create
                                Profile</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">{% now "l, d F Y" %}</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Welcome, {{ user.first_name }} {{ user.last_name }} </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/show_messages.html
<div class="container text-center font-weight-bold">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <strong>{{ message|safe }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ message|safe }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ message|safe }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message|safe }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
