accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.LogoutPageView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangePageView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDonePageView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetPageView.as_view(), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDonePageView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmPageView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompletePageView.as_view(), name='password_reset_complete'),
    path('signup/', views.SignUpPageView.as_view(), name="signup"),
    path('profile/', views.profile_page_view, name='profile'),
    # path('profile/update/<int:pk>/', views.ProfileUpdatePageView.as_view(), name='profile_update'),
    path('profile/update/<int:pk>/', views.profile_update_page_view, name='profile_update'),
    path('profile/create/<int:id>', views.ProfileCreatePageView.as_view(), name='profile_create'),
]

epica_test/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('pica.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pica/urls.py
from django.urls import path
from . import views

app_name = "pica"
urlpatterns = [
    path('', views.home, name="home"),
    path('create_departemen/', views.CreateDepartemenView.as_view(), name="create_departemen"),
    path('update_departemen/<int:pk>/', views.UpdateDepartemenView.as_view(), name="update_departemen"),
    path('delete_departemen/<int:pk>/', views.DeleteDepartemenView.as_view(), name="delete_departemen"),
    path('create_forum/', views.CreateForumView.as_view(), name="create_forum"),
    path('update_forum/<int:pk>/', views.UpdateForumView.as_view(), name="update_forum"),
    path('delete_forum/<int:pk>/', views.DeleteForumView.as_view(), name="delete_forum"),
    path('create_company/', views.CreateCompanyView.as_view(), name="create_company"),
    path('update_company/<int:pk>/', views.UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<int:pk>/', views.DeleteCompanyView.as_view(), name="delete_company"),
    path('create_peserta/', views.CreatePesertaView.as_view(), name="create_peserta"),
    path('update_peserta/<int:pk>/', views.UpdatePesertaView.as_view(), name="update_peserta"),
    path('delete_peserta/<int:pk>/', views.DeletePesertaView.as_view(), name="delete_peserta"),
    path('add_peserta/<int:pk>/', views.add_peserta, name="add_peserta"),
    path('masukkan_peserta/<int:pk1>/<int:pk2>/', views.masukkan_peserta, name="masukkan_peserta"),
    path('hapus_peserta/<int:pk1>/<int:pk2>/', views.hapus_peserta, name="hapus_peserta"),
    path('create_pica/<int:pk>/', views.create_pica, name="create_pica"),
    path('update_pica/<int:pk1>/<int:pk2>/', views.update_pica, name="update_pica"),
    path('update_pica_action/<int:pk1>/<int:pk2>/', views.update_pica_action, name="update_pica_action"),
    path('add_pic/<int:pk1>/<int:pk2>/', views.add_pic, name="add_pic"),
    path('meet_render_pdf/<int:pk>/', views.meet_render_pdf, name="meet_render_pdf"),
    path('meet_signature_pdf/<int:pk>/', views.meet_signature_pdf, name="meet_signature_pdf"),
    path('send_meet_render_pdf/<int:pk>/', views.send_meet_render_pdf, name="send_meet_render_pdf"),
    path('masukkan_pic/<int:pk1>/<int:pk2>/<int:pk3>/<str:pk4>/', views.masukkan_pic, name="masukkan_pic"),
    path('hapus_pic/<int:pk1>/<int:pk2>/<int:pk3>/', views.hapus_pic, name="hapus_pic"),
    path('create_meeting/', views.CreateMeetingView.as_view(), name="create_meeting"),
    path('history_meeting/', views.history_meeting, name="history_meeting"),
    path('meeting_dashboard/<int:pk>/<int:hs>/', views.meeting_dashboard, name="meeting_dashboard"),
    path('update_dashboard/<int:pk>/', views.UpdateDashboardView.as_view(), name="update_dashboard"),
    path('list_pica/<int:pk>/', views.list_pica, name="list_pica"),
    path('create_activity/<int:pk>/', views.create_activity, name="create_activity"),
    path('update_activity/<int:pk>/', views.update_activity, name="update_activity"),
    path('delete_activity/<int:pk>/', views.delete_activity, name="delete_activity"),
    path('list_activity/<int:pk>/<int:ctr>/', views.list_activity, name="list_activity"),
    path('add_topik/<int:pk>/', views.add_topik, name="add_topik"),
    path('delete_topik/<int:pk1>/<int:pk2>/', views.delete_topik, name="delete_topik"),
    path('masukkan_topik/<int:pk1>/<int:pk2>/', views.masukkan_topik, name="masukkan_topik"),
    path('hapus_topik/<int:pk1>/<int:pk2>/', views.hapus_topik, name="hapus_topik"),
    path('topik_expired_check/', views.topik_expired_check, name="topik_expired_check"),
    path('list_open_pica/', views.list_open_pica, name="list_open_pica"),
    path('search_topik/', views.search_topik, name="search_topik"),
    path('search_all/', views.search_all, name="search_all"),
    path('notify_all/', views.notify_all, name="notify_all"),
]

pica/views.py
from datetime import datetime, date
from io import BytesIO
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from .models import Company, Peserta, DivDept, Meeting, Forum, Topik, Activity, Signature
from .forms import *
from django.urls import reverse_lazy
from django.http import HttpResponse
from xhtml2pdf import pisa
from django.template.loader import get_template


@login_required(login_url='accounts:login')
def home(request):
    topiks = Topik.objects.filter(topik2user=request.user)
    hari_ini = date.today()
    meetings = Meeting.objects.filter(meeting_date__gte=hari_ini)
    context = {
        'topiks': topiks,
        'meetings': meetings,
    }
    return render(request, 'home.html', context)


def meet_render_pdf(request, pk):
    meet = get_object_or_404(Meeting, pk=pk)
    template_path = 'pica/pdf_daily_meeting.html'
    peserta = Peserta.objects.filter(peserta2meeting=meet, bod=True)
    all_peserta = Peserta.objects.filter(peserta2meeting=meet)
    topik = Topik.objects.filter(topik2meeting=meet)

    context = {
        'meet': meet,
        'peserta': peserta,
        'topik': topik,
        'all_peserta': all_peserta,
    }
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="meeting.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse("Terjadi error pada <pre>" + html + "</pre>")
    return response


def meet_signature_pdf(request, pk):
    meet = get_object_or_404(Meeting, pk=pk)
    template_path = 'pica/pdf_signature_meeting.html'
    peserta = Peserta.objects.filter(peserta2meeting=meet, bod=True)
    all_peserta = Peserta.objects.filter(peserta2meeting=meet)
    topik = Topik.objects.filter(topik2meeting=meet)
    forum = Forum.objects.get(pk=meet.meeting2forum.pk)
    signs = Signature.objects.filter(signature2forum=forum).order_by('-presdir')
    # for sig in signs:
    #
    context = {
        'meet': meet,
        'peserta': peserta,
        'topik': topik,
        'all_peserta': all_peserta,
        'signs': signs,
    }
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="signature_meeting.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse("Terjadi error pada <pre>" + html + "</pre>")
    return response


def send_meet_render_pdf(request, pk):
    meet = get_object_or_404(Meeting, pk=pk)
    template_path = 'pica/pdf_daily_meeting.html'
    peserta = Peserta.objects.filter(peserta2meeting=meet, bod=True)
    all_peserta = Peserta.objects.filter(peserta2meeting=meet)
    to_email = []
    for pes in peserta:
        to_email.append(pes.email)

    topik = Topik.objects.filter(topik2meeting=meet)
    person = {}
    # to_pic = {}
    for top in topik:
        pics = User.objects.filter(user2topik=top)
        lst = []
        # lst_pic = []
        for pic in pics:
            lst.append(pic.first_name + " " + pic.last_name)
            # lst_pic.append(pic.email)
        person[top.pk] = lst
        # to_pic[top.pk] = lst_pic
    context = {
        'meet': meet,
        'peserta': peserta,
        'topik': topik,
        'person': person,
        'all_peserta': all_peserta,
    }
    template = get_template(template_path)
    html = template.render(context)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    pdf = result.getvalue()
    filename = "MEETING " + str(meet.meeting_date) + ".pdf"
    mail_subject = "Summary Meeting " + str(meet.meeting_date)
    mail_message = "Dengan Hormat, \n\n" + "Berikut MoM Meeting hari ini. \n" + "Mohon untuk di-follow up. \n" + "Demikian disampaikan, terimakasih atas perhatiannya. \n\n" + \
                   "Regards, \n\n" + "CPMD \n"

    email = EmailMessage(
        mail_subject,
        mail_message,
        settings.EMAIL_HOST_USER,
        to_email,
    )
    email.attach(filename, pdf, 'application/pdf')
    email.send(fail_silently=False)

    #############################
    # Render special topik
    #############################
    today = datetime.today().strftime("%Y-%m-%d")
    for top in topik:
        dept = get_object_or_404(DivDept, departemen2topik=top)
        activities = Activity.objects.filter(activity2topik=top)
        pics = User.objects.filter(user2topik=top)
        context = {
            'top': top,
            'activities': activities,
            'pics': pics,
        }
        template_path = 'pica/pdf_pic_topik.html'
        to_email = []
        cc_email = []
        for pic in pics:
            to_email.append(pic.email)
        # cc_email.append(dept.email_dir_in_charge)
        # cc_email.append(dept.email_dept_head_in_charge)
        template = get_template(template_path)
        html = template.render(context)
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
        pdf = result.getvalue()
        filename = "Topik Meeting " + str(today) + ".pdf"
        mail_subject = "Topik Meeting " + str(today)
        mail_message = "Mohon agar dapat segera ditindak lanjuti topik seperti terlampir."
        email = EmailMessage(
            mail_subject,
            mail_message,
            settings.EMAIL_HOST_USER,
            to_email,
            cc=cc_email,
        )
        email.attach(filename, pdf, 'application/pdf')
        email.send(fail_silently=False)

    return HttpResponse("Email sent!")


def list_pica(request, pk):
    topiks = Topik.objects.filter(topik2user=pk).exclude(status="CLOSE").order_by('due_date')

    context = {
        'topiks': topiks,
    }
    return render(request, 'pica/list_pica.html', context)


def create_activity(request, pk):
    topik = get_object_or_404(Topik, pk=pk)
    usr = get_object_or_404(User, pk=request.user.pk)
    acts = topik.topik2activity.all().order_by('-date_activity')
    if request.method == "POST":
        form = CreateActivityForm(data=request.POST)
        if form.is_valid():
            act = topik.topik2activity.filter(date_activity=request.POST['date_activity'])
            if act:
                messages.error(request, "Activity untuk tanggal yang sama sudah ada.")
                return redirect('pica:create_activity', pk)
                pass
            else:
                new_form = form.save(commit=False)
                new_form.activity2topik = topik
                new_form.activity2user = usr
                new_form.save()
                return redirect("pica:create_activity", topik.pk)
    else:
        form = CreateActivityForm()
    context = {
        'form': form,
        'acts': acts,
        'topik': topik,
    }
    return render(request, 'pica/create_activity.html', context)


def list_activity(request, pk, ctr):
    topik = get_object_or_404(Topik, pk=pk)
    usr = get_object_or_404(User, pk=request.user.pk)
    acts = topik.topik2activity.all().order_by('-date_activity')
    form = ListActivityForm()
    context = {
        'form': form,
        'acts': acts,
        'topik': topik,
        'ctr': ctr,
    }
    return render(request, 'pica/list_activity.html', context)


def update_activity(request, pk):
    act = get_object_or_404(Activity, pk=pk)
    topik = get_object_or_404(Topik, pk=act.activity2topik.pk)
    if request.method == "POST":
        form = UpdateActivityForm(request.POST, instance=act)
        if form.is_valid():
            form.save()
            return redirect("pica:create_activity", act.activity2topik.pk)
    else:
        form = UpdateActivityForm(instance=act)
    context = {
        'form': form,
        'topik': topik,
    }
    return render(request, 'pica/update_activity.html', context)


def delete_topik(request, pk1, pk2):
    topik = get_object_or_404(Topik, pk=pk2)
    meet_id = pk1

    if request.method == "POST":
        topik.delete()
        messages.success(request, "Data berhasil di hapus.")
        return redirect('pica:meeting_dashboard', meet_id)
    context = {
        'topik': topik,
        'meet': meet_id,
    }
    return render(request, 'pica/delete_topik.html', context)


def delete_activity(request, pk):
    act = get_object_or_404(Activity, pk=pk)
    topik = act.activity2topik.pk
    if request.method == "POST":
        act.delete()
        return redirect('pica:create_activity', topik)
    context = {
        'act': act,
    }
    return render(request, 'pica/delete_activity.html', context)


def create_pica(request, pk):
    topiks = Topik.objects.exclude(status="CLOSE").order_by('due_date')
    if request.method == "POST":
        form = CreatePicaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("pica:create_pica", pk)
    else:
        form = CreatePicaForm()
    context = {
        'form': form,
        'topiks': topiks,
        'meet': pk,
    }
    return render(request, 'pica/create_pica.html', context)


def update_pica(request, pk1, pk2):
    topik = get_object_or_404(Topik, pk=pk1)

pica/templates/pica/add_pic.html
{% extends 'base.html' %}
{% block title %}Add Person In Charge{% endblock %}
{% block content %}
    <div class="container-fluid">
        <br>
        <h3>Add Person In Charge</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="nama_pic"></label>
                        <input type="text" class="form-control" name="nama_pic"
                               placeholder="Masukkan nama PIC" id="nama_pic">
                    </div>
                </div>
                <div class="col-lg-1">
                    <div class="form-group">
                        <label for="search_nama"></label>
                        <button type="submit" class="btn btn-primary form-control" id="search_nama">Search</button>
                    </div>
                </div>
                <div class="col-lg-1">
                    <div class="form-group">
                        <label for="exit"></label>
                        <a class="btn btn-warning form-control" id="exit"
                                {#                           href="{% url 'pica:create_pica' meet %}"><b>Exit</b></a>#}
                           href="{% url 'pica:meeting_dashboard' meet 1%}"><b>Exit</b></a>
                    </div>
                </div>
            </div>
        </form>
        <br>
    </div>
    <div class="row container-fluid">
        <div class="col">
            <h6>Pilih PIC</h6>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>BOD</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                {% for usr in sisa_user %}
                    <tr>
                        <td>{{ usr.nama }}</td>
                        <td>{{ usr.email }}</td>
                        {% if usr.bod %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                        <td><a class="btn btn-sm btn-primary"
                               href="{% url 'pica:masukkan_pic' topik.pk usr.pk meet 'Y' %}">PIC</a></td>
                        <td><a class="btn btn-sm btn-secondary"
                               href="{% url 'pica:masukkan_pic' topik.pk usr.pk meet 'N' %}">Known By</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col">
            <h6>PIC (assigned)</h6>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>Full Name</th>
                    <th>email</th>
                    <th>Status</th>
                    <th></th>
                </tr>
                </thead>
                {% for usrt in user_topik %}
                    <tr>
                        <td>{{ usrt.nama }}</td>
                        <td>{{ usrt.email }}</td>
                        {% if usrt.email in email_list %}
                            <td>PIC</td>
                        {% else %}
                            <td>Known By</td>
                        {% endif %}
                        <td><a class="btn btn-sm btn-danger"
                               href="{% url 'pica:hapus_pic' topik.pk usrt.pk meet %}">Remove</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <br>
    </div>
{% endblock %}

pica/templates/pica/create_company.html
{% extends 'base.html' %}
{% block title %}Create Company{% endblock %}
{% block content %}
    <br>
    <style>
        #tabel_header {
            font-size: 14px;
        }

        #tabel_detail {
            font-size: 12px;
        }

        #nama_company {
            font-weight: bold;
        }

        h4 {
            color: darkblue;
        }
    </style>
    <div class="row container-fluid">
        <div class="col">
            <br>
            <h4>Create Company</h4>
            <hr>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Create</button>
                <a href="{% url 'pica:home' %}">
                    <button class="btn btn-danger" type="button">Exit</button>
                </a>
            </form>
        </div>
        <div class="col border border-secondary rounded">
            <h4>List of Company</h4>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr id="tabel_header">
                    <th>Company Code</th>
                    <th>Company Name</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                {% for company in companies %}
                    <tr id="tabel_detail">
                        <td id="nama_company">{{ company.name }}</td>
                        <td>{{ company.description }}</td>
                        <td><a class="btn btn-sm btn-primary btn-sm"
                               href="{% url 'pica:update_company'  company.id %}">Edit</a></td>
                        <td><a class="btn btn-sm btn-danger btn-sm"
                               href="{% url 'pica:delete_company'  company.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <br>
{% endblock %}

pica/templates/pica/create_departemen.html
{% extends 'base.html' %}
{% block title %}Create Function{% endblock %}
{% block content %}
    <br>
    <style>
        #tabel_header {
            font-size: 14px;
        }

        #tabel_detail {
            font-size: 12px;
        }

        #nama_departemen {
            font-weight: bold;
        }

        h4 {
            color: darkblue;
        }
    </style>
    <div class="row container-fluid">
        <div class="col">
            <br>
            <h4>Create Function</h4>
            <hr>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Create</button>
                <a href="{% url 'pica:home' %}">
                    <button class="btn btn-danger" type="button">Exit</button>
                </a>
            </form>
        </div>
        <div class="col border border-secondary rounded">
            <h4>List of Function</h4>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr id="tabel_header">
                    <th>Nama Div/Dept</th>
                    <th>Description</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                {% for dept in depts %}
                    <tr id="tabel_detail">
                        <td id="nama_departemen">{{ dept.name }}</td>
                        <td id="description">{{ dept.description }}</td>
                        <td><a class="btn btn-sm btn-primary btn-sm"
                               href="{% url 'pica:update_departemen'  dept.id %}">Edit</a></td>
                        <td><a class="btn btn-sm btn-danger btn-sm"
                               href="{% url 'pica:delete_departemen'  dept.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <br>
{% endblock %}

pica/templates/pica/delete_forum.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Forum{% endblock %}
{% block content %}
    <br><br>
    <div class="col-lg-4 offset-lg-4">
        <h4>Delete Forum</h4>
        <br>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure want to delete this data?</p>
            <br>
            <p>Nama forum : {{ forum.nama_forum }}</p>
            <p>Keterangan : {{ forum.keterangan }}</p>
            <p>Group Code : {{ forum.group_code }}</p>
            <br><br>
            <p>
                <button class="btn btn-danger" type="submit">Delete</button>
                <a href="{% url 'pica:create_forum' %}">
                    <button class="btn btn-primary" type="button">Cancel</button>
                </a>
            </p>
        </form>
    </div>
{% endblock %}

pica/templates/pica/delete_peserta.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Peserta{% endblock %}
{% block content %}
    <br><br>
    <div class="col-lg-4 offset-lg-4">
        <h4>Delete Peserta</h4>
        <br>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure want to delete this data?</p>
            <br>
            <p>Name : {{ peserta.nama }}</p>
            <p>Email : {{ peserta.email }}</p>
            <p>Status BOD : {{ peserta.bod }}</p>
            <br><br>
            <p>
                <button class="btn btn-danger" type="submit">Delete</button>
                <a href="{% url 'pica:create_peserta' %}">
                    <button class="btn btn-primary" type="button">Cancel</button>
                </a></p>
        </form>
    </div>
{% endblock %}

pica/templates/pica/history_meeting.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <style>
        #meeting_date {
            font-weight: bold;
        }

        #tabel_header {
            font-size: 13px;
        }

        #tabel_detail {
            font-size: 12px;
        }
    </style>
    <div class="row container-fluid">
        <div class="col">
            <h5>History Data Meeting</h5>
            <br>
            <form action="" method="post" id="meeting_form">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Submit">
                <a class="btn btn-danger" href="{% url 'pica:home' %}" role="button">Cancel</a>
                <br>
            </form>
            <br>
        </div>
        <br>
        <div class="col border border-secondary rounded">
            <h5>Meeting List</h5>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr id="tabel_header">
                    <th>Tanggal</th>
                    <th>Forum</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Location</th>
                    <th></th>
                </tr>
                </thead>
                {% for meet in meets %}
                    <tr id="tabel_detail">
                        <td id="meeting_date">{{ meet.meeting_date|date:"l, d M Y" }}</td>
                        <td>{{ meet.meeting2forum.nama_forum }}</td>
                        <td>{{ meet.start_time | time:"g A" }}</td>
                        <td>{{ meet.end_time | time:"g A" }}</td>
                        <td>{{ meet.location }}</td>
                        <td><a class="btn btn-sm btn-secondary btn-sm"
                               href="{% url 'pica:meeting_dashboard' meet.pk 0 %}">Dashboard</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

pica/templates/pica/list_open_pica.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <div class="row container-fluid">
        <div class="col-lg">
            <h5>List Open PICA</h5>
            <br>
            <form action="" method="post" id="meeting_form">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Submit">
{#                <a class="btn btn-danger" href="{% url 'pica:home' %}" role="button">Cancel</a>#}
                <br>
            </form>
            <br>
        </div>
        <table class="table table-lg table-striped">
            <thead class="thead-dark">
            <tr id="tabel_header">
                <th>Topik</th>
                <th>Problem</th>
                <th>Action</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Expired</th>
                <th></th>
            </tr>
            </thead>
            {% for topik in topiks %}
                <tr id="tabel_detail">
                    <td id="nama_departemen">{{ topik.nama_topik }}</td>
                    <td>{{ topik.problem|safe }}</td>
                    <td>{{ topik.action|safe }}</td>
                    <td>{{ topik.due_date|date:"d M Y" }}</td>
                    <td>{{ topik.status }}</td>
                    {% if topik.expired %}
                        <td>Yes</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                    <td><a class="btn btn-sm btn-primary btn-sm"
                           href="{% url 'pica:list_activity' topik.pk 4 %}">Activity</a></td>
                    <td></td>
                </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td><a class="btn btn-sm btn-primary btn-sm"
                       href="{% url 'accounts:home' %}">Back to Homepage</a></td>
                <td><a class="btn btn-sm btn-danger btn-sm"
                       href="{% url 'pica:notify_all' %}">Notify All</a></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <br>
    </div>
{% endblock %}

pica/templates/pica/list_pica.html
{% extends 'base.html' %}
{% block title %}List PICA{% endblock %}
{% block content %}
    <br>
    <style>
        #tabel_header {
            font-size: 14px;
        }

        #tabel_detail {
            font-size: 12px;
        }

        #due_date {
            font-weight: bold;
        }

        h4 {
            color: darkblue;
        }
    </style>
    <div class="row container-fluid">
        <div class="col">
            <h4 class="text-center">List PICA</h4>
            <a href="{% url 'pica:home' %}" class="btn btn-primary">Back to Home</a>
            <br>
            <br>
            <table class="table table-lg table-striped">
                <thead class="thead-dark">
                <tr id="tabel_header">
                    <th>Topik</th>
                    <th>Problem</th>
                    <th>Action</th>
                    <th>Div/Dept.</th>
                    <th>Company</th>
                    <th>Due Date</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                {% for topik in topiks %}
                    <tr id="tabel_detail">
                        <td>{{ topik.nama_topik }}</td>
                        <td>{{ topik.problem|safe }}</td>
                        <td>{{ topik.action|safe }}</td>
                        <td>{{ topik.topik2divdept.name }}</td>
                        <td>{{ topik.topik2company.name }}</td>
                        <td id="due_date">{{ topik.due_date }}</td>
                        <td>{{ topik.status }}</td>
                        <td><a class="btn btn-sm btn-primary btn-sm"
                               href="{% url 'pica:create_activity' topik.pk %}">Activity</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <br>
{% endblock %}